language: node_js
node_js:
  - '0.10.33'
before_script:
  - 'npm install -g bower karma gulp jshint'
  - 'npm install' # install npm packages
  - 'bower install' # install bower packages
script: gulp test
